### ISSUE TITLE
ModuleNotFoundError: No module named 'custom_components.everlights3-main.diagnostics'

### ISSUE THREAD

**Issue by kylerw** [weswitt/everlights3#1]
Logger: homeassistant.helpers.integration_platform
Source: helpers/integration_platform.py:50
First occurred: 10:12:10 PM (10 occurrences)
Last logged: 10:13:15 PM

Unexpected error importing everlights3/system_health.py
Unexpected error importing everlights3/energy.py
Unexpected error importing everlights3/cast.py
Unexpected error importing everlights3/significant_change.py
Unexpected error importing everlights3/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.everlights3-main.diagnostics'

**Comment by weswitt** [comment]
this looks like something may be wrong with your ha install. my integration is nowhere on the stack trace. i have no idea what is going on here.

**Comment by weswitt** [comment]
what version of ha are your running?

**Comment by kylerw** [comment]
2023.11.3

**Comment by weswitt** [comment]
how exactly are you using the integration? i need a lot more details as i cannot repro this in my testing.

**Comment by kylerw** [comment]
Downloaded the code, unzipped and moved into 'custom_components' directory. Restarted HA. Added integration (setup pop up is blank with no instructions), enter IP of Bridge. 

The integration is added successfully but does not properly reflect state/status and the error appears in the log.

**Comment by weswitt** [comment]
well i fixed the issue with the light state not being reflected. but i do not see the error that you see. what other integrations & addons do you have installed?

**Comment by kylerw** [comment]
It appears to have been a permission issue. Got it resolved.

**Comment by weswitt** [comment]
what specifically was causing this?

**Comment by kylerw** [comment]
I am not certain which files/folders were causing the issue but I did a chown and chmod to the folder which seemed to resolve it. Then I forked your repo and restructured for HACS support and download/install from HACS also didn't have the issue.
